### ISSUE TITLE
Day 2 review: Nice work, weldone 

### ISSUE THREAD

**Issue by Jonniie** [imosfinest/coders-den#3]
What's up with level 3  🌚

**Comment by gudycode** [comment]
Thank you so much for the review...I will update level 3.

**Comment by gudycode** [comment]
I think I'm struggling to understand some of the  questions in level 3...

**Comment by Jonniie** [comment]
You can drop that on the group, or you can ask in your next class.

**Comment by gudycode** [comment]
Sorry...but is this the same John @Games night?

**Comment by Jonniie** [comment]
Yeah 👋

**Comment by gudycode** [comment]
Oh oh.

**Comment by gudycode** [comment]
Please send me a message  on WhatsApp.

**Comment by Jonniie** [comment]
Ok, I will.
